Repository dis-moi/backend, pull requests merged in 2020-07, with the labels that each got.

#243 chore: clean intentions
  app/DoctrineMigrations/Version20200628124311.php
  src/AppBundle/DataFixtures/ORM/LoadNoticeData.php
  src/AppBundle/Entity/Notice.php
  src/AppBundle/Form/IntentionType.php
  src/AppBundle/Helper/NoticeIntention.php
Labels: reviewable

#244 chore: remove obsolete migration endpoint
  src/AppBundle/Controller/Api/PostMigrateDomainNames.http
  src/AppBundle/Controller/Api/PostMigrateDomainNamesAction.php
Labels: reviewable

#245 fix: check that shown notices are public, unexpired and from enabled contributors
  src/AppBundle/Controller/ContributorAdminController.php
  src/AppBundle/Entity/Contributor.php
  src/AppBundle/Entity/Notice.php
  src/AppBundle/Repository/MatchingContextRepository.php
  src/AppBundle/Repository/NoticeRepository.php
  tests/AppBundle/Controller/Api/GetNoticeActionTest.php
  tests/AppBundle/Controller/Api/PostNoticeRatingActionTest.php
  tests/e2e/GetContributorTest.php
  tests/e2e/GetNoticeTest.php
  tests/e2e/GetNoticesTest.php
Labels: bug, reviewable

#249 fix(api): get notices by contributor
  src/AppBundle/Repository/NoticeRepository.php
Labels: bug, production, reviewable

#251 feat(api): add message version without links (anchors)
  docs/openapi.json
  src/AppBundle/Serializer/NoticeNormalizer.php
  src/Domain/Service/MessagePresenter.php
Labels: enhancement, reviewable

#253 fix: unable to set picture for contributor without starred notice
  src/AppBundle/Entity/Contributor.php
Labels: bug, production, reviewable

#254 feat(stats): new labels for backoffice notices stats
  app/Resources/translations/messages.fr.yml
Labels: enhancement, reviewable

#261 fix: can’t set notice without screenshot
  src/AppBundle/Entity/Notice.php
Labels: bug, reviewable

#262 fix: can’t create contributor
  app/config/easyadmin.yml
  src/AppBundle/Entity/Contributor.php
Labels: bug, reviewable

#260 feat: Set default notices sorting order to most recent first.
  src/AppBundle/Repository/NoticeRepository.php
Labels: enhancement, reviewable

#257 feat(presenter): use br for single line breaks
  src/Domain/Service/MessagePresenter.php
  tests/Domain/Service/MessagePresenterTest.php
  tests/e2e/GetNoticeTest.php
Labels: enhancement, reviewable

#256 feat: contributors can relay notices
  app/DoctrineMigrations/Version20200702095935.php
  app/Resources/translations/messages.fr.yml
  app/config/easyadmin.yml
  docker-compose.yml
  docs/openapi.json
  src/AppBundle/Controller/AdminController.php
  src/AppBundle/DataFixtures/ORM/LoadContributorData.php
  src/AppBundle/DataFixtures/ORM/LoadNoticeData.php
  src/AppBundle/DataFixtures/ORM/LoadSubscriptionData.php
  src/AppBundle/Entity/Contributor.php
  src/AppBundle/Entity/Notice.php
  src/AppBundle/Entity/Relay.php
  src/AppBundle/Repository/MatchingContextRepository.php
  src/AppBundle/Serializer/ContributorNormalizer.php
  src/AppBundle/Serializer/NoticeNormalizer.php
  tests/AppBundle/Entity/ContributorTest.php
  tests/e2e/GetContributorTest.php
  tests/e2e/GetMatchingContextsTest.php
  tests/e2e/PostContributorRatingTest.php
  tests/e2e/PostSubscriptionsTest.php
Labels: enhancement, reviewable

#258 feat(domains): proto-domains
  app/DoctrineMigrations/Version20200716152334.php
  app/Resources/translations/messages.fr.yml
  app/config/easyadmin.yml
  src/AppBundle/Entity/DomainName.php
  src/AppBundle/Entity/MatchingContext.php
  src/AppBundle/Form/MatchingContextType.php
  tests/AppBundle/Entity/MatchingContextTest.php
  tests/e2e/GetMatchingContextsTest.php
Labels: enhancement, reviewable
