Repository dis-moi/backend, pull requests merged in 2021-03, with the labels that each got.

#316 Goutte fix 304
  config/packages/vich_uploader.yaml
  src/Entity/Ability/VichFilenamer.php
  src/Entity/Contributor.php
Labels: bug

#301 feat(admin): allow user role in BO
  config/packages/easy_admin.yaml
  config/packages/security.yaml
Labels: enhancement

#317 Goutte's review 00
  .env
  CONTRIBUTING.md
  README.md
  alias
  src/Controller/.gitignore
  src/Entity/.gitignore
Labels: enhancement

#326 chore: Add a pre-commit hook fixing the code style.
  Makefile
  composer.json
  composer.lock
  symfony.lock
Labels: DX
