Repository dis-moi/backend, pull requests merged in 2021-07, with the labels that each got.

#408 Perf : Save ratings count in notices entities
  .env
  composer.json
  composer.lock
  config/packages/easy_admin.yaml
  config/packages/messenger.yaml
  migrations/Version20210704210627.php
  src/Controller/AdminApiController.php
  src/Controller/Api/V3/PostNoticeRating.http
  src/Controller/Api/V3/PostNoticeRatingAction.php
  src/DataFixtures/NoticeFixtures.php
  src/Entity/Notice.php
  src/Message/NoticeRated.php
  src/MessageHandler/NoticeRatedHandler.php
  src/Repository/RatingRepository.php
  src/Serializer/V3/NoticeNormalizer.php
  symfony.lock
  tests/Controller/Api/V3/PostNoticeRatingActionTest.php
  translations/messages.fr.yml
Labels: Size M :shirt:, analytics, enhancement, production, reviewable

#391 fix(subscription): Fix empty subscription update date crash
  src/Domain/Service/SubscriptionsTrackingService.php
Labels: bug :beetle:

#287 doc: add matching contexts flow
  docs/matching_contexts_flow.mmd
Labels: WIP
